---
title: "Analyses_Bifid"
author: "rubenladeira"
date: "02/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librairies

```{r,message=F,warning=F}

library(data.table)
library(phyloseq)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(ggsignif)
library(microbiome)
library(dplyr)
library(ggforce)
library(rlang)

source("functions.R")

```

## Import des données

```{r,message=F,warning=F}

load(file = "study_after_QC.rda")

```


## Objet phyloseq et transformation des Count en abondance relative

```{r,message=F,warning=F}

# définition du nom des lignes pour map

mapp <- map %>%
  tibble::column_to_rownames("sample_id") 

# création de l'object phyloseq

## matrices

otu <- as.matrix(otus)


taxo <- as.matrix(tax)

##

```


## Prévalence

```{r,message=F,warning=F,fig.height=25, fig.width=25}

otu <- otu_table(otu, taxa_are_rows = TRUE)
mapp <- sample_data(mapp)
taxo <- tax_table(taxo)

phy <- phyloseq(otu, mapp, taxo)

# on sélectionne que les adultes

phy <- subset_samples(phy, body_site == "stool")

phy_initial <- subset_samples(phy, antibiotics_current_use == "no")



## la fonction de référence pour regrouper les sample est la somme, on doit dc normaliser les lignes pour chaque groupe

map_s <- data.frame(phy@sam_data)

taxon <- data.frame(phy@tax_table)

pre <- data.frame(t(phy@otu_table))

```


## Objet Phyloseq

```{r,message=F,warning=F}

## on a un tableau avec les abondances relatives moyennes en fonction des catégories

## table_pourc <- data.frame(phy@otu_table)

## on veut savoir quelles espèces sont bifid ou non

especes <- taxon %>%
  mutate(bifid =
           case_when(Genus == 'Bifidobacterium' ~ "oui", 
                     TRUE ~ "non")) %>%
  select(Species, bifid) %>%
  rownames_to_column(.,"tax")


map <- map_s %>%
  rownames_to_column(.,"sample_id")
  

tax <- taxon %>%
  rownames_to_column(.,"tax") %>%
  select(tax)
  

#rownames(prevalence_group_mean) <- gsub(".", "|", rownames(prevalence_group_mean))

prevalence_group_mean <- pre %>%
  rownames_to_column(.,"sample_id") %>%
  merge(.,map, by="sample_id") %>%
  select(-sample_id) %>%
  group_by_at('disease') %>%
  summarise_all(., funs(mean(.>0))) %>%
  column_to_rownames(var = 'disease') %>%
  t(.) %>%
  data.frame()
  
rownames(prevalence_group_mean) <- gsub("\\.", "\\|", rownames(prevalence_group_mean))

  
prevalence_group_mean <- prevalence_group_mean %>%
  rownames_to_column(.,"tax") %>%
  merge(., especes, by="tax") %>%
  column_to_rownames(.,var='tax')

## prevalence group_mean contient les prévalences qui nous intéresse, il nous reste a ajouter les colonnnes bifi/non bifid puis mutate !


tabl_rangee <- prevalence_group_mean %>%
  arrange(desc(Control)) %>% 
  group_by(bifid) %>%
  slice(1:5) %>%
  as.data.frame(.) %>%
  gather(., disease, abundance, Control:BD) %>%
  group_by(bifid) %>%
  data.frame()


```


## Plot

```{r,message=F,warning=F,fig.height=8, fig.width=10}



  
p <- ggplot(tabl_rangee, aes(x = Species, y = disease, color=disease))+
  geom_point(aes(size=abundance)) +
  guides(size="none")  +
  labs( x= "", y = "", size = "", fill ="", color="") +
  scale_x_discrete(limits = tabl_rangee$Species[1:10]) +
  scale_y_discrete(limits = rev(levels(map$disease))) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 40, hjust = 1),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  geom_text(aes(label = paste0(round(tabl_rangee$abundance*100,2),"%")), vjust=-1.5)

p


#ggsave("mean_bacteria_all_disease.png")

```


## Plot

```{r,message=F,warning=F,fig.height=8, fig.width=10}



plot_rond <- function(category, facteur_control){

  target_column = rlang::sym(facteur_control)

  prevalence_group_mean <- pre %>%
    rownames_to_column(.,"sample_id") %>%
    merge(.,map, by="sample_id") %>%
    select(-sample_id) %>%
    group_by_at(category) %>%
    summarise_all(., funs(mean(.>0))) %>%
    column_to_rownames(var = category) %>%
    t(.) %>%
    data.frame()
  
  rownames(prevalence_group_mean) <- gsub("\\.", "\\|", rownames(prevalence_group_mean))

  
  prevalence_group_mean <- prevalence_group_mean %>%
    rownames_to_column(.,"tax") %>%
    merge(., especes, by="tax") %>%
    column_to_rownames(.,var='tax')

  tabl_rangee <- prevalence_group_mean %>%
    arrange(desc(!!rlang::sym(target_column))) %>%
    group_by(bifid) %>%
    slice(1:5) %>%
    as.data.frame(.) %>%
    gather(., !!rlang::sym(category), abundance, -c(Species, bifid)) %>%
    group_by(bifid) %>%
    data.frame()




  p <- ggplot(tabl_rangee, aes_string(x = "Species", y = category, color=category))+
    geom_point(aes(size=abundance)) +
    guides(size="none")  +
    labs( x= "", y = "", size = "", fill ="", color=category) +
    scale_x_discrete(limits = tabl_rangee$Species[1:10]) +

    scale_y_discrete(limits = rev(levels(map[[category]]))) +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 40, hjust = 1),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    geom_text(aes(label = paste0(round(tabl_rangee$abundance*100,2),"%")), vjust=-1.5)

  p

}

## filtering data depends on studied factor

## filtering
phy <- subset_samples(phy_initial, age_category == "adult")
## initialize pre
pre <- data.frame(t(phy@otu_table))

plot_rond("disease", 'Control')

## filtering
phy <- subset_samples(phy_initial, age_category == "adult")
phy <- subset_samples(phy, disease == "Control")
## initialize pre
pre <- data.frame(t(phy@otu_table))

plot_rond("westernized", 'yes')

## filtering
phy <- subset_samples(phy_initial, disease == "Control")
## initialize pre
pre <- data.frame(t(phy@otu_table))

plot_rond("age_category", 'adult')

```


