---
title: "Analyses_Bifid"
author: "rubenladeira"
date: "02/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librairies

```{r,message=F,warning=F}

library(data.table)
library(phyloseq)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(ggsignif)

```

## Import des données

```{r,message=F,warning=F}

load(file = "study_after_QC.rda")

```

## Analyse de la composition des bifis suivant l'âge


```{r,message=F,warning=F}

## fonction pour sélectionner les abondances relatives des bifid
## par groupe d'âge


# d'abord je m'occupe des otus
  
# je sélectionne toutes les espèces du genre bifid
  
tax_modif <- tax %>%
  filter(Genus=="Bifidobacterium")
  

otus_modif <- data.frame(otus) %>%
  # j'ai que les bifids
  filter(row.names(otus)  %in% row.names(tax_modif))

## j'ajoute les espèces
otus_modif <- cbind(otus_modif, Species = tax_modif$Species)

otus_modif <- data.frame(otus_modif) %>%
  group_by(Species) %>%
  summarise_all(.,sum)

otus_modif <- data.frame(otus_modif)
rownames(otus_modif) <- otus_modif$Species
otus_modif <- otus_modif[,-1]

  
# on transpose pour simplifier le traitement
otus_modif <- data.frame(t(otus_modif)) %>%
  # je veux le nom des espèces
  rownames_to_column("sample_id")
  
# on va calculer les abondances de toutes ces espèces par groupe d'âge

map_modif <- map %>%
  filter(antibiotics_current_use=="no") %>%
  left_join(otus_modif, by="sample_id") %>%
  group_by(age_category) %>%
  select(matches("age_category") | starts_with('Bifidobacterium')) %>%
  summarise_all(.,sum)


```

## Plot

```{r,message=F,warning=F}

# on va enlever les espèces qui sont présentes dans aucune tranche d'âge

map_modif <- map_modif %>%
  select(where(~ any(. !=0)))


# on prend les 10 espèces les + abondantes seulement

ten_species <- map_modif %>% 
  select(-age_category) %>% 
  summarise_all(funs(sum))

ten_species <- colnames(ten_species[order(ten_species)[1:10]])


# on veut les abondances relatives dans un groupe seulement
```

## On reshape les données pour le plot
```{r,message=F,warning=F}
reshaped_map <- map_modif %>%
  gather(Espece, Reads, matches("Bifido"))

rownames(reshaped_map) <- ten_species <-gsub(".", " ", rownames(reshaped_map), fixed=TRUE)

reshaped_map <- reshaped_map %>%
  group_by(age_category) %>% 
  mutate(relAbundance = Reads / sum(Reads))

reshaped_map$age_category <- factor(reshaped_map$age_category, levels=c("newborn", "child", "schoolage", "adult","senior"))
```

## on va sommer par groupe d'espèce et prendre les proportion les plus élevées
```{r,message=F,warning=F}

ten_species <- reshaped_map %>%
  group_by(Espece) %>%
  summarise(sumAb = sum(relAbundance)) %>%
  arrange(desc(sumAb))

# on sélectionne les 10
ten_species <- ten_species$Espece[1:10]

reshaped_map <- reshaped_map %>%
  filter(Espece %in% ten_species)

reshaped_map$Espece <-gsub(".", " ", reshaped_map$Espece, fixed=TRUE)

```


# plot
```{r,message=F,warning=F}

ggplot(reshaped_map, aes(x = age_category, y = relAbundance, fill = Espece)) + 
  geom_bar(stat = "identity") +
  theme_minimal() + labs(x = NULL, y = "Relative Abundance", title = "Relative Abundance of Bifidobacterium Species") +
  labs(fill= "10 most common species") + coord_flip()

```



## fonction pour sélectionner les abondances relatives des bifid
## par groupe d'âge

```{r,message=F,warning=F}
# d'abord je m'occupe des otus

levels = c("no","yes")  
  
# on va calculer les abondances de toutes ces espèces par groupe

map_modif <- map %>%
  filter(antibiotics_current_use=="no" & age_category=="adult") %>%
  left_join(otus_modif, by="sample_id") %>%
  group_by(non_westernized) %>%
  select(matches("non_westernized") | starts_with('Bifidobacterium')) %>%
  summarise_all(.,sum)


# on va enlever les espèces qui sont présentes dans aucune tranche d'âge

map_modif <- map_modif %>%
  select(where(~ any(. !=0)))


# on prend les 10 espèces les + abondantes seulement

ten_species <- map_modif %>% 
  select(-c('non_westernized')) %>% 
  summarise_all(funs(sum))

ten_species <- colnames(ten_species[order(ten_species)[1:10]])

# on veut les abondances relatives dans un groupe seulement

reshaped_map <- map_modif %>%
  gather(Espece, Reads, matches("Bifido"))

rownames(reshaped_map) <- ten_species <-gsub(".", " ", rownames(reshaped_map), fixed=TRUE)

reshaped_map <- reshaped_map %>%
  group_by(non_westernized) %>%
  mutate(relAbundance = Reads / sum(Reads))

reshaped_map$non_westernized <- factor(reshaped_map$non_westernized, levels=levels)

ten_species <- reshaped_map %>%
  group_by(Espece) %>%
  summarise(sumAb = sum(relAbundance)) %>%
  arrange(desc(sumAb))

# on sélectionne les 10
ten_species <- ten_species$Espece[1:10]

reshaped_map <- reshaped_map %>%
  filter(Espece %in% ten_species)

reshaped_map$Espece <-gsub(".", " ", reshaped_map$Espece, fixed=TRUE)

ggplot(reshaped_map, aes(x = non_westernized, y = relAbundance, fill = Espece)) + 
  geom_bar(stat = "identity") +
  theme_minimal() + labs(x = "Non westernized", y = "Relative Abundance", title = "Relative Abundance of Bifidobacterium Species") +
  labs(fill= "10 most common species") + coord_flip()


```
### test de chi 2

# package SpiecEasi

```{r,message=F,warning=F}
# d'abord je m'occupe des otus

levels = c("no","yes")  
  
# on va calculer les abondances de toutes ces espèces par groupe

map_modif <- map %>%
  filter(age_category == "adult") %>%
  left_join(otus_modif, by="sample_id") %>%
  group_by(antibiotics_current_use) %>%
  select(matches("antibiotics_current_use") | starts_with('Bifidobacterium')) %>%
  summarise_all(.,sum)


# on va enlever les espèces qui sont présentes dans aucune tranche d'âge

map_modif <- map_modif %>%
  select(where(~ any(. !=0)))


# on prend les 10 espèces les + abondantes seulement

ten_species <- map_modif %>% 
  select(-c('antibiotics_current_use')) %>% 
  summarise_all(funs(sum))

ten_species <- colnames(ten_species[order(ten_species)[1:10]])

# on veut les abondances relatives dans un groupe seulement

reshaped_map <- map_modif %>%
  gather(Espece, Reads, matches("Bifido"))

rownames(reshaped_map) <- ten_species <-gsub(".", " ", rownames(reshaped_map), fixed=TRUE)

reshaped_map <- reshaped_map %>%
  group_by(antibiotics_current_use) %>%
  mutate(relAbundance = Reads / sum(Reads))

reshaped_map$antibiotics_current_use <- factor(reshaped_map$antibiotics_current_use, levels=levels)

ten_species <- reshaped_map %>%
  group_by(Espece) %>%
  summarise(sumAb = sum(relAbundance)) %>%
  arrange(desc(sumAb))

# on sélectionne les 10
ten_species <- ten_species$Espece[1:12]

reshaped_map <- reshaped_map %>%
  filter(Espece %in% ten_species) %>%
  filter(!is.na(antibiotics_current_use))

reshaped_map$Espece <-gsub(".", " ", reshaped_map$Espece, fixed=TRUE)

ggplot(reshaped_map, aes(x = antibiotics_current_use, y = relAbundance, fill = Espece)) + 
  geom_bar(stat = "identity") +
  theme_minimal() + labs(x = "Antibiotics current use", y = "Relative Abundance", title = "Relative Abundance of Bifidobacterium Species") +
  labs(fill= "10 most common species") + coord_flip()


```



