---
title: "Package SpiecEasi"
author: "rubenladeira"
date: "02/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librairies

```{r,message=F,warning=F}

library(data.table)
library(phyloseq)
library(tidyverse)
library(dplyr)
library(ggpubr)
library(ggplot2)
library(devtools)
library(SpiecEasi)
library(Matrix)
library(igraph)

```

## Load des fichiers

```{r,message=F,warning=F}

setwd("..")
#load("study_after_QC.rda")

```

## Processing

```{r,message=F,warning=F}

# définition du nom des lignes pour map

mapp <- map %>% 
  tibble::column_to_rownames("sample_id") 

# création de l'object phyloseq

## matrices

otu <- as.matrix(otus)


# on va enlever le premier mot de Species dans tax pour décharger

taxo <- data.frame(tax)

tax$Species <- stringr::word(tax$Species, -1)

taxo <- as.matrix(taxo)

##

```

## Objet Phyloseq

```{r,message=F,warning=F}

otu <- otu_table(otu, taxa_are_rows = TRUE)
mapp <- sample_data(mapp)
taxo <- tax_table(taxo)

phy <- phyloseq(otu, mapp, taxo)

```

## Fitre et abondance relative

```{r,message=F,warning=F}

phy = subset_taxa(phy, Genus=="Bifidobacterium")


```

## test

```{r,message=F,warning=F}

MSP_abundance_matrix_rounder <- as.matrix(phy@otu_table)

MSP_abundance_matrix_rounded %>%
  tibble::rownames_to_column("msp") %>%
  mutate_if(is.numeric, function(x) x/sum(x)) %>%
  tibble::column_to_rownames("msp") %>%
  BiotypeR::noise.removal(percent=1) %>% rownames() -> msp_select

msp_select = union(msp_select,c("msp_lrhamnosus","msp_1025"))


MSP_abundance_matrix_rounded[msp_select,] %>% t %>%
  spiec.easi(., method='mb', lambda.min.ratio=1e-2,
             nlambda=20, pulsar.params=list(rep.num=20, ncores=32)) -> MSP_spiec_easi

```
