---
title: "PFAM analysis"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Librairies

```{r,message=F,warning=F}



source(file = "functions.R")

```

## import data

```{r,message=F,warning=F}

mags_tax_gene_id_eggnog <- readr::read_csv2("data-raw/mags_tax_gene_id_eggnog.csv") %>%
   select(-X1)


### load matrix of distances

load(file = "bif_mags_dist.rda")

```

## phytase analysis

```{r,message=F,warning=F}

mags_tax_gene_id_eggnog %>%
  select(genome_name, assigned_species, sample_name) %>%
  mutate(genome_name= paste0(genome_name,".fa")) %>%
  unique() -> genome_name_assigned_species_df


genome_name_assigned_species_df %>%
  group_by(assigned_species) %>%
  summarise(n_genomes=n()) 

```

## phytase

```{r}


phytase_pfam_desc = c("His_Phos_2","Y_phosphatase3", "Phytase", "Phytase-like", "fn3_PAP")


mags_tax_gene_id_eggnog %>% 
  filter(grepl(paste(phytase_pfam_desc, collapse="|"), PFAMs)) %>%
  select(assigned_species, eggNOG_OGs,PFAMs, Description) %>%
  group_by(assigned_species, eggNOG_OGs,PFAMs, Description) %>%
  summarise(n=n()) -> bif_phytase 

bif_phytase %>% write.csv2(file="bif_MAGs_phytase.csv")
  
  
bif_phytase %>%
  reshape2::dcast(eggNOG_OGs+PFAMs+Description~assigned_species, fill=0)



```

### phytase and metadata


```{r}
load("curated_v3_otu_tax.rda")

sampleMetadata %>% select(sample_id, non_westernized,age_category) -> CMD_metadata
```
#### phytase adult western vs no western

```{r fig.height=6, fig.width=12}

genome_name_assigned_species_df %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  group_by(assigned_species,non_westernized) %>%
  summarise(n_genomes=n()) 


phytase_pfam_desc = c("His_Phos_2","Y_phosphatase3", "Phytase", "Phytase-like", "fn3_PAP")

mags_tax_gene_id_eggnog %>% 
  filter(grepl(paste(phytase_pfam_desc, collapse="|"), PFAMs)) %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(age_category == "adult") -> mags_tax_gene_id_eggnog_phytase_metadata
  

mags_tax_gene_id_eggnog_phytase_metadata %>% 
  select(genome_name, assigned_species, eggNOG_OGs, PFAMs, Description, non_westernized) %>% #dim
  unique %>% #dim
  group_by(assigned_species, eggNOG_OGs,PFAMs, Description,non_westernized) %>%
  summarise(n=n()) %>%
  
  merge(
    
    genome_name_assigned_species_df %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(age_category == "adult") %>%
  group_by(assigned_species,non_westernized) %>%
  summarise(n_genomes=n()) , 
  by=c("assigned_species","non_westernized")) %>%
  
  arrange(assigned_species,eggNOG_OGs) %>%
  mutate(prevalence=n/n_genomes) %>%
  ggplot() + 
  geom_bar(aes(x=Description,y=prevalence,fill=non_westernized), stat="identity", position = "dodge") +
  facet_grid(~assigned_species %>% gsub(" ","\n",.), scales = "free_x", space = "free_x") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
  
  
```
#### phytase age category western

```{r fig.height=6, fig.width=12}


phytase_pfam_desc = c("His_Phos_2","Y_phosphatase3", "Phytase", "Phytase-like", "fn3_PAP")

mags_tax_gene_id_eggnog %>% 
  filter(grepl(paste(phytase_pfam_desc, collapse="|"), PFAMs)) %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(non_westernized == "no") %>%
  mutate(age_category = age_category %>% forcats::fct_relevel("adult", after=3))  -> mags_tax_gene_id_eggnog_phytase_metadata
  

mags_tax_gene_id_eggnog_phytase_metadata %>% 
  select(genome_name, assigned_species, eggNOG_OGs, PFAMs, Description, age_category) %>% #dim
  unique %>% #dim
  group_by(assigned_species, eggNOG_OGs,PFAMs, Description,age_category) %>%
  summarise(n=n()) %>%
  
  merge(
    
    genome_name_assigned_species_df %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(non_westernized == "no") %>%
  group_by(assigned_species,age_category) %>%
  summarise(n_genomes=n()) , 
  by=c("assigned_species","age_category")) %>%
  
  arrange(assigned_species,eggNOG_OGs) %>%
  mutate(prevalence=n/n_genomes) %>%
  ggplot() + 
  geom_bar(aes(x=Description,y=prevalence,fill=age_category), stat="identity", position = "dodge") +
  facet_grid(~assigned_species %>% gsub(" ","\n",.), scales = "free_x", space = "free_x") +
  scale_fill_brewer(type="div", palette = 2) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  
  


```



## PUP 

```{r}

readr::read_tsv("data-raw/all.bif.nr95.dbPUP.hits.tsv") %>%
  dplyr::rename(pup_annot=annot) %>%
  select(-tax) %>%
  merge(mags_tax_gene_id_eggnog, by="id_rep", all = FALSE) %>%
  select(assigned_species, eggNOG_OGs, pup_family, Description, pup_annot) %>%
  mutate(Description = paste(Description,pup_annot)) %>%
  group_by(assigned_species, eggNOG_OGs, pup_family, Description) %>%
  summarise(n=n()) -> bif_PUP

bif_PUP %>% write.csv2(file="bif_MAGs_PUP.csv")


bif_PUP %>%
  reshape2::dcast(eggNOG_OGs+pup_family+Description~assigned_species, fill=0)


```

### pup  adult western vs no western


```{r fig.height=6, fig.width=12}


readr::read_tsv("data-raw/all.bif.nr95.dbPUP.hits.tsv") %>%
  dplyr::rename(pup_annot=annot) %>%
  select(-tax) %>%
  merge(mags_tax_gene_id_eggnog, by="id_rep", all = FALSE) %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(age_category == "adult") %>%
  select(genome_name, assigned_species, eggNOG_OGs, pup_family, Description, non_westernized) %>% #dim
  unique %>% #dim
  group_by(assigned_species, eggNOG_OGs,pup_family, Description,non_westernized) %>%
  summarise(n=n()) %>%
  
  merge(
    
    genome_name_assigned_species_df %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(age_category == "adult") %>%
  group_by(assigned_species,non_westernized) %>%
  summarise(n_genomes=n()) , 
  by=c("assigned_species","non_westernized")) %>%
  
  arrange(assigned_species,eggNOG_OGs) %>%
  mutate(prevalence=n/n_genomes) %>%
  ggplot() + 
  geom_bar(aes(x=pup_family,y=prevalence,fill=non_westernized), stat="identity", position = "dodge") +
  facet_grid(~assigned_species %>% gsub(" ","\n",.), scales = "free_x", space = "free_x") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



  


```


### pup  age category western 


```{r fig.height=6, fig.width=12}


readr::read_tsv("data-raw/all.bif.nr95.dbPUP.hits.tsv") %>%
  dplyr::rename(pup_annot=annot) %>%
  select(-tax) %>%
  merge(mags_tax_gene_id_eggnog, by="id_rep", all = FALSE) %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(non_westernized == "no") %>%
  mutate(age_category = age_category %>% forcats::fct_relevel("adult", after=3)) %>%
  select(genome_name, assigned_species, eggNOG_OGs, pup_family, Description, age_category) %>% #dim
  unique %>% #dim
  group_by(assigned_species, eggNOG_OGs,pup_family, Description,age_category) %>%
  summarise(n=n()) %>%
  
  merge(
    
    genome_name_assigned_species_df %>%
  merge(CMD_metadata, by.x="sample_name", by.y="sample_id") %>%
  filter(non_westernized == "no") %>%
  group_by(assigned_species,age_category) %>%
  summarise(n_genomes=n()) , 
  by=c("assigned_species","age_category")) %>%
  
  arrange(assigned_species,eggNOG_OGs) %>%
  mutate(prevalence=n/n_genomes) %>%
  ggplot() + 
  geom_bar(aes(x=pup_family,y=prevalence,fill=age_category), stat="identity", position = "dodge") +
  facet_grid(~assigned_species %>% gsub(" ","\n",.), scales = "free_x", space = "free_x") +
  scale_fill_brewer(type="div", palette = 2) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



  


```


## cazy

```{r}
readr::read_tsv("data-raw/cazy_dbcann.tsv") %>%
  merge(mags_tax_gene_id_eggnog,., by.x="id_rep", by.y="Gene ID", all = FALSE) %>%
  select(assigned_species, eggNOG_OGs, cazy_family, Description) %>%
  group_by(assigned_species, eggNOG_OGs, cazy_family, Description) %>%
  summarise(n=n()) -> bif_cazy

bif_cazy %>% write.csv2(file="bif_MAGs_cazy.csv")





```


```{r}

rbind(
bif_phytase %>%
  mutate(gene_type="PHYTASE") %>%
  dplyr::rename(family = PFAMs) ,

bif_PUP %>%
  mutate(gene_type="PUPs") %>%
  dplyr::rename(family = pup_family),

bif_cazy %>%
  mutate(gene_type="CAZy") %>%
  dplyr::rename(family = cazy_family)


) %>% reshape2::dcast(eggNOG_OGs+gene_type+family+Description~assigned_species, fill=0, value.var = "n") %>%
arrange(gene_type, family) -> bif_prevalence_phytase_cazy_pup
  

readr::write_csv2(x = bif_prevalence_phytase_cazy_pup, file="bif_prevalence_phytase_cazy_pup.csv")



```


