---
title: "differential_analysis"
author: "ruben"
date: "06/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library

```{r, message=F,warning=F}

library(DESeq2)
library(dplyr)
library(data.table)
library(microbiome)
library(phyloseq)
library(tibble)
library(fantaxtic)
library(glue)
library(pheatmap)

source(file = "functions.R")

```

## Import data

```{r, message=F,warning=F}

## load the phy object

name = "phy_deseq_analysis_150"

if(!(name %in% list.files())) {
  
  print(paste0("you do not have the file ",name," , please run run_spiec_easi_analyse.Rmd before."))
  
} else {
  load(name)
}

## we will merge the bifidotype to the meta_data

bifidotypes <- fread('enterotype_DMM_adult_subjects') %>%
  select(sample_id, bifidotype)

metadata <- data.frame(sample_data(phy)) %>%
  rownames_to_column("sample_id") %>%
  left_join(., bifidotypes, by="sample_id") %>%
  column_to_rownames(var="sample_id")
## transform enterotype as bifidotype and factor
  
# convert  to factor

metadata$bifidotype <- factor(metadata$bifidotype)


sample_data(phy) <- sample_data(metadata)




#otu_test_filtered <- otu_test %>%
#  filter_all(any_vars(. %in% c(0)))

```

## Control

```{r, message=F,warning=F}

## import otu table

tax <- data.frame(phy@tax_table)

otu <- data.frame(phy@otu_table)

## check if species have 0 count on every sample

which(rowSums(otu) == 0) ## all species have at least a positive count on 1 sample at least


```

## Deseq

```{r cars}

# Get size factors
# Create a DESeq2 temp object

dds_temp = phyloseq_to_deseq2(phy, ~ 1)

# Size factors estimated with filtered genera - all samples - poscounts

dds_temp <- estimateSizeFactors(dds_temp, type="poscounts")

sizefactors_filter <- sizeFactors(dds_temp)

# Remove NA values for the core pattern and create DESeq2 object

genera_temp <- prune_samples(!is.na(sample_data(phy)[["bifidotype"]]), phy)

dds <- phyloseq_to_deseq2(genera_temp, ~ 1)

samp_keep <- sample_names(genera_temp)


# Add size factors and design

design(dds) <- as.formula(glue("~ bifidotype"))

sizeFactors(dds) <- sizefactors_filter[samp_keep]

# Global pattern effect (using precomputed size factors)

dds_res1 <- DESeq(dds, test="LRT", reduced= as.formula(glue("~ 1")))

res_glob <- results(dds_res1, alpha=0.05)

# Get list of significant genera (global effect)

signif_genera <- rownames(res_glob[which(res_glob$padj<0.05),])

```

## Deseq

```{r cars}
## enterotype : mettre Bif. 1 etc, charactère, et le mettre en facteur

## name of deseqfile

dds_res2 <- DESeq(dds, test="Wald")

co = matrix(as.character(combn(levels(factor(data.frame(sample_data(phy))[,"bifidotype"])), 2)),nrow=2) # Generate pairs of groups

output_FDR <- matrix(0,ncol=ncol(co),nrow=length(signif_genera))

rownames(output_FDR) <- signif_genera

colnames(output_FDR) <- apply(co,MARGIN=2,paste,collapse="-")

output_LogFC <- output_FDR

output_baseMean <- output_FDR

for(elem in 1:ncol(co)){ # Loop on comparisons
  
  # Perform contrast
  
  res_onecomp <- results(dds_res2,
                         contrast=c("bifidotype",
                                    glue("{co[1,elem]}"),
                                    glue("{co[2,elem]}"))
                         , alpha=0.05)
  
  # Extract unadjusted pvalue of genera with significant global effect, and adjust it with BH
  
  output_FDR[,elem] <- p.adjust(res_onecomp[signif_genera,"pvalue"],method="BH")
  output_LogFC[,elem] <- res_onecomp[signif_genera,"log2FoldChange"]
  output_baseMean[,elem] <- res_onecomp[signif_genera,"baseMean"]
}


```

## Deseq

```{r cars}

# Extract log2FC for each group to plot them

dds2 <- dds

design(dds2) <- as.formula(glue("~ -1 + bifidotype"))

dds_res3 <- DESeq(dds2, test="Wald")

groups <- levels(colData(dds_res2)[,"bifidotype"])

order_LogFC <- matrix(0,ncol=length(groups),nrow=length(signif_genera))

rownames(order_LogFC) <- signif_genera

colnames(order_LogFC) <- groups

order_lfcSE <- order_LogFC

order_baseMean <- order_LogFC

for (group in groups) {
  res_temp <- results(dds_res3, name = paste0("bifidotype",group))
  order_LogFC[,group] <- res_temp[signif_genera,"log2FoldChange"]
  order_lfcSE[,group] <- res_temp[signif_genera,"lfcSE"]
  order_baseMean[, group] <- res_temp[signif_genera, "baseMean"]
}

```

## load Deseq results

```{r cars}

## save the log 2 fold change results

name_FC = "output_LogFC_7"

name_FDR = "output_FDR_7"

name_baseMean <- "output_baseMean_7"

output_LogFC_7 <- output_LogFC

output_FDR_7 <- output_FDR

output_baseMean_7 <- output_baseMean

if(!(name_FC %in% list.files())) {
  
  save(output_LogFC, file = name_FC)
  
  save(output_FDR, file = name_FDR)
  
  save(output_baseMean, file = name_baseMean)
  
} else {
  load(name_FC)
  load(name_FDR)
  load(name_baseMean)
}

data_logFC <- output_LogFC

data_FDR <- output_FDR

data_baseMean <- output_baseMean

```

## Post-hoc comparisons

```{r cars,fig.height=20, fig.width=20}

rownames(data_logFC) <- get_species(tax, rownames(data.frame(data_logFC)))

rownames(data_FDR) <- get_species(tax, rownames(data.frame(data_FDR)))

rownames(data_baseMean) <- get_species(tax, rownames(data.frame(data_baseMean)))

```

## Post-hoc comparisons

```{r cars,fig.height=20, fig.width=20}


# log2FC
melted_data_logFC <- melt(data_logFC)
colnames(melted_data_logFC)[3] <- "Log2FC"

# -log10(FDR)
data_adj_pval <- -log10(data_FDR)
melted_data_adj_pval <- melt(data_adj_pval)
melted_data_adj_pval$color <- 0


melted_data_adj_pval$color[melted_data_adj_pval$value <= -log10(0.1)] <- "NS"
melted_data_adj_pval$color[melted_data_adj_pval$value > -log10(0.1) & melted_data_adj_pval$value <= -log10(0.05)] <- "Trend"
melted_data_adj_pval$color[melted_data_adj_pval$value > -log10(0.05)] <- "Signif"
melted_data_adj_pval$color = factor(melted_data_adj_pval$color, levels = c("NS","Trend","Signif"))



# Data to plot with the right order
complete_data <- merge(melted_data_logFC, melted_data_adj_pval, by=c("Var1","Var2"))
complete_data$Var2 <- factor(complete_data$Var2, levels=colnames(data_logFC))

colors_dots <- c('#f7f7f7','#969696','#252525')

names(colors_dots) <- c("NS","Trend","Signif")

## we suppress bifidobacterium species so that they do not hide other signals

complete_data$Var1 <- gsub("Bifidobacterium", "B.", complete_data$Var1) ## simplify bifido name

complete_data <- complete_data %>%
  filter(!grepl("B.", Var1))


```

## Filter species based on basemean

```{r cars,message=F,warning=F}

species_to_select <- data_baseMean %>%
  data.frame(.) %>%
  filter(!grepl("Bifidobacterium", row.names(.))) %>%
  filter(row.names(.) %in% complete_data$Var1) %>%
  select(1) %>%
  top_n(30) %>%
  rownames(.) %>%
  as.character(.)

complete_data_filtered <- complete_data %>%
  filter(Var1 %in% species_to_select)

```


# Plot the heatmap

```{r cars,fig.height=10, fig.width=10}

ggplot(data = complete_data_filtered, aes(x=Var2, y=Var1, fill=Log2FC)) + 
  geom_tile(color="white") +
  scale_fill_distiller(direction = -1, palette = "RdBu", limits=c(floor(min(complete_data_filtered$Log2FC)), ceiling(max(complete_data_filtered$Log2FC))), name="Effect size\nLog2FC") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1),
        axis.text.y = element_text(size=10),
        axis.title = element_blank(),
        plot.title=element_text(hjust=0.5, face="bold", size=15),
        plot.margin = unit(c(10,0,0,0), "pt")) +
  coord_fixed() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  geom_point(aes(size=value, color=color)) +
  labs(size = "Evidence\n-log10(p-value)", color="Significance") +
  scale_color_manual(values=colors_dots) +
  scale_size(limits=c(0,30),breaks=c(5,10,15,23),range=c(1,4))


```


## Prepare data for a pheatmap for better representation

```{r cars,fig.height=10, fig.width=10}

pheat <- complete_data_filtered %>%
  select(Var1, Var2, Log2FC) %>%
  spread(key = Var2, value = Log2FC) %>%
  column_to_rownames("Var1")

data <- complete_data_filtered

p_values <- complete_data_filtered %>%
  select(Var1, Var2, value) %>%
  spread(key = Var2, value = value) %>%
  column_to_rownames("Var1")
  
signif <- complete_data_filtered %>%
  mutate(., color =
           case_when(color == 'NS' ~ "",
                     color == 'Trend' ~ "*",
                     color == 'Signif' ~ "***")) %>%
  select(Var1, Var2, color) %>%
  spread(key = Var2, value = color) %>%
  column_to_rownames("Var1")

```

## Plotting pheatmap

```{r cars,fig.height=8, fig.width=8}

pheatmap(pheat, display_numbers = signif)

```

## Plotting heatmap

```{r cars,fig.height=20, fig.width=15}


pheatmap <- pheatmap(output_LogFC,
                     legend_breaks = c( -15, -10, -5, 0, 5, 10, max(output_LogFC)), 
                     legend_labels = c('-15', '-10', '-5', '0', '5', '10', "Log2FC"),
                     legend = TRUE,  cluster_cols = FALSE,)


```